
networks:
    opportune-network:
      driver: bridge
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
    networks:
      - opportune-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5  

  gateway-service:
    image: muhammadadhil/gateway:v4
    build:
      context: ../gateway
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "4002:4002"
    env_file: 
      - ../gateway/.env.production  
    networks:
      - opportune-network    


  user-service:
    image: muhammadadhil/opportune-userservice:v4
    build:
      context: ./userService
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3015:3015"
    depends_on:
      rabbitmq:
        condition: service_healthy  
    env_file:
      - ./userService/.env.production
    networks:
      - opportune-network

  post-service:
    image: muhammadadhil/opportune-postservice:v4
    build:
      context: ./postService
      dockerfile: Dockerfile
    container_name: post-service
    ports:
      - "3020:3020"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./postService/.env.production
    networks:
      - opportune-network  

  contract-service:
    image: muhammadadhil/opportune-contractservice:v4
    build:
      context: ./contractService
      dockerfile: Dockerfile
    container_name: contract-service
    ports:
      - "3030:3030"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file: 
      - ./contractService/.env.production  
    networks:
      - opportune-network

  messaging-service:
    image: muhammadadhil/opportune-messagingservice:v4
    build:
      context: ./messagingService
      dockerfile: Dockerfile
    container_name: messaging-service
    ports:
      - "3060:3060"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file: 
      - ./messagingService/.env.production  
    networks:
      - opportune-network    

  payment-service:
    image: muhammadadhil/opportune-paymentservice:v4
    build:
      context: ./paymentService
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "3040:3040"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file: 
      - ./paymentService/.env.production  
    networks:
      - opportune-network        

  manage-service:
    image: muhammadadhil/opportune-manageservice:v4
    build:  
      context: ./manageService
      dockerfile: Dockerfile
    container_name: manage-service
    ports:
      - "3010:3010" 
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file: 
      - ./manageService/.env.production 
    networks:
      - opportune-network  

  notification-service:
    image: muhammadadhil/opportune-notificationservice:v4
    build:
      context: ./notificationService
      dockerfile: Dockerfile
    container_name: notification-service 
    ports:
      - "3050:3050"
    depends_on:
      rabbitmq:
        condition: service_healthy
    env_file:
      - ./notificationService/.env.production
    networks:
      - opportune-network  
          
