
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" 
    networks:
      - opportune-network

  # gateway-service:
  #   image: muhammadadhil/gateway:latest
  #   container_name: gateway-service
  #   ports:
  #     - "4002:4002"  


  user-service:
    image: muhammadadhil/opportune-userservice:latest
    container_name: user-service
    ports:
      - "3015:3015"
    depends_on: 
      - rabbitmq  
    env_file:
      - ./userService/.env
    networks:
      - opportune-network

  # post-service:
  #   image: muhammadadhil/opportune-postservice:v1
  #   container_name: post-service
  #   ports:
  #     - "3020:3020"

  # contract-service:
  #   image: muhammadadhil/opportune-contractservice:v1
  #   container_name: contract-service
  #   ports:
  #     - "3060:3030"

  # messaging-service:
  #   image: muhammadadhil/opportune-messagingservice:v1
  #   container_name: messaging-service
  #   ports:
  #     - "3060:3060"    

  # manage-service:
  #   image: muhammadadhil/opportune-manageservice:v1
  #   container_name: manage-service
  #   ports:
  #     - "3010:3010" 

  # notification-service:
  #   image: muhammadadhil/opportune-notificationservice:v1
  #   container_name: notification-service
  #   ports:
  #     - "3050:3050"

  # payment-service:
  #   image: muhammadadhil/opportune-paymentservice:v1
  #   container_name: payment-service
  #   ports:
  #     - "3040:3040"          

networks:
    opportune-network:
      driver: bridge