apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
data:
  JWT_SECRET: 'VEhJUzFJU1RIMjNTRUNSMzQyMUVUQ09ERTc1NkZPUkFDRVNT'

---

apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
type: Opaque
data:
  MONGODB_URL: 'bW9uZ29kYitzcnY6Ly9tdWhhbW1hZGFkaGlsOTM0OmFhZGhpOTM0QGNsdXN0ZXIwLmI4ZmllZnUubW9uZ29kYi5uZXQvb3Bwb3J0dW5lLWZyZWVsYW5jZS1hcHA/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA='
  JWT_ACCESSTOKEN_SECRET: 'VEhJUzFJU1RIMjNTRUNSMzQyMUVUQ09ERTc1NkZPUkFDRVNT' # Base64 encoded
  JWT_REFRESHTOKEN_SECRET: 'Q09ERTc1NkZPUkFDRVNTVEhJUzFJU1RIMjNTRUNSMzQyMUVU'
  GOOGLE_CLIENT_SECRET: 'R09DU1BYLTVqQkdJZzJ4c2gzN2lESzBaUnhoLWhyZl9LcFA='
  NODEMAILER_USER: 'b3Bwb3J0dW5lZnJlZWxhbmNlYXBwQGdtYWlsLmNvbQ=='
  NODEMAILER_USER_PASSWORD: 'cnp5diB1Z2ptIG56YWsgZWRwbQ=='  
  AWS_ACCESS_KEY: QUtJQVpQUEY3VzJNTDNEQ0FJN1M=
  AWS_SECRET_KEY: NUFDQktsVVRhM0o1NTNNc1M2WjRyeHlUV0FldHRaamxabUp4TGZweA==


---

apiVersion: v1
kind: Secret
metadata:
  name: post-service-secret
type: Opaque
data:
  MONGODB_URL: bW9uZ29kYitzcnY6Ly9tdWhhbW1hZGFkaGlsOTM0OmFhZGhpOTM0QGNsdXN0ZXIwLmI4ZmllZnUubW9uZ29kYi5uZXQvb3Bwb3J0dW5lLWpvYmFuZEdpZ1NlcnZpY2U/cmV0cnlXcml0ZXM9dHJ1ZSZhcHBOYW1lPUNsdXN0ZXIw
  JWT_SECRET: VEhJUzFJU1RIMjNTRUNSMzQyMUVUQ09ERTc1NkZPUkFDRVNT
  AWS_ACCESS_KEY: QUtJQVpQUEY3VzJNTDNEQ0FJN1M=
  AWS_SECRET_KEY: NUFDQktsVVRhM0o1NTNNc1M2WjRyeHlUV0FldHRaamxabUp4TGZweA==
  

---

apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secret
type: Opaque
data:
  MONGODB_URL: bW9uZ29kYitzcnY6Ly9tdWhhbW1hZGFkaGlsOTM0OmFhZGhpOTM0QGNsdXN0ZXIwLmI4ZmllZnUubW9uZ29kYi5uZXQvb3Bwb3J0dW5lLXBheW1lbnRTZXJ2aWNlP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIw # Base64 encoded value of MONGODB_URL
  STRIPE_SECRET_KEY: c2tfdGVzdF81MVFRU284RnNTcExZQjVVaTBhaFVJcktSRW9HR3ZOT0FzMThQTkgyTktkM1RxTU80dTJJcnRxMFpPczdCMzJ6bWZhYXFnNEN6dXVLcHVVSnY4TWVRSUg4WjAwV2xIT3hsM2c= # Base64 encoded value of STRIPE_SECRET_KEY
  # STRIPE_WEBHOOK_SECRET: d2hzZWNfNTM0Nzl4Y2Y2ZWM2NjEzZjMwNWM4YmNmODg5cGM4OGZkM2Y2OTgyaTRubW9WMiY0Zmw9 # Base64 encoded value of STRIPE_WEBHOOK_SECRET
  STRIPE_WEBHOOK_SECRET: d2hzZWNfWmRMRmUxTGxoamE1WWZUY0FzeXljZUJ6UzhZNGxOTVAK

  
---

apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secret
type: Opaque
data:
  MONGODB_URL: bW9uZ29kYitzcnY6Ly9tdWhhbW1hZGFkaGlsOTM0OmFhZGhpOTM0QGNsdXN0ZXIwLmI4ZmllZnUubW9uZ29kYi5uZXQvb3Bwb3J0dW5lLW5vdGlmaWNhdGlvblNlcnZpY2U/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjAK

---

apiVersion: v1
kind: Secret
metadata:
  name: messaging-service-secret
type: Opaque
data:
  MONGODB_URL: bW9uZ29kYitzcnY6Ly9tdWhhbW1hZGFkaGlsOTM0OmFhZGhpOTM0QGNsdXN0ZXIwLmI4ZmllZnUubW9uZ29kYi5uZXQvb3Bwb3J0dW5lLW1lc3NhZ2luZ1NlcnZpY2U/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA=  

---

apiVersion: v1
kind: Secret
metadata:
  name: manage-service-secret
type: Opaque
data:
  MONGODB_URL: bW9uZ29kYitzcnY6Ly9tdWhhbW1hZGFkaGlsOTM0OmFhZGhpOTM0QGNsdXN0ZXIwLmI4ZmllZnUubW9uZ29kYi5uZXQvb3Bwb3J0dW5lLW1hbmFnZVNlcnZpY2U/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjA= 
  JWT_ACCESSTOKEN_SECRET: VEhJUzFJU1RIMjNTRUNSMzQyMUVUQ09ERTc1NkZPUkFDRVNT
  JWT_REFRESHTOKEN_SECRET: Q09ERTc1NkZPUkFDRVNTVEhJUzFJU1RIMjNTRUNSMzQyMUVU

---

apiVersion: v1
kind: Secret
metadata:
  name: contract-service-secret
type: Opaque
data:
  MONGODB_URL: bW9uZ29kYitzcnY6Ly9tdWhhbW1hZGFkaGlsOTM0OmFhZGhpOTM0QGNsdXN0ZXIwLmI4ZmllZnUubW9uZ29kYi5uZXQvb3Bwb3J0dW5lLWNvbnRyYWN0U2VydmljZT9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1DbHVzdGVyMA==
  AWS_ACCESS_KEY: "QUtJQVpQUEY3VzJNTDNEQ0FJN1M="  # Base64 encoded
  AWS_SECRET_KEY: "NUFDQktsVVRhM0o1NTNNc1M2WjRyeHlUV0FldHRaamxabUp4TGZweA=="  # Base64 encoded
