name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - userService
          - postService
          - paymentService
          - notificationService
          - messagingService
          - manageService
          - contractService
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for ${{ matrix.service }}
        run: |
          SERVICE_NAME=$(echo "${{ matrix.service }}" | tr '[:upper:]' '[:lower:]')
          docker build -t muhammadadhil/opportune-$SERVICE_NAME:latest ./backend/services/${{ matrix.service }}
          docker push muhammadadhil/opportune-$SERVICE_NAME:latest

  # Separate job to build and push gateway if needed
  build-and-push-gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push additional Docker image
        run: |
          docker build -t muhammadadhil/opportune-gateway:latest ./backend/gateway
          docker push muhammadadhil/opportune-gateway:latest

  deploy:
    runs-on: ubuntu-latest
    needs: [build-and-push, build-and-push-gateway]
    strategy:
      matrix:
        service:
          - gateway
          - userservice
          - postservice
          - paymentservice
          - notificationservice
          - messagingservice
          - manageservice
          - contractservice
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Get GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'opportune-cluster'
          location: 'us-central1-a'
          project_id: 'opportune-backend'

      - name: Deploy ${{ matrix.service }}
        run: |
          SERVICE_NAME=${{ matrix.service }}
          kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}=muhammadadhil/opportune-$SERVICE_NAME:latest
          kubectl rollout restart deployment/${SERVICE_NAME}
          kubectl rollout status deployment/${SERVICE_NAME}